services: 
  api_dotnet_model:
    build: 
      context: .
      dockerfile: Dockerfile
    image: pqa_dotnet_api:latest
    container_name: pqa_dotnet_container
    ports: 
      - "8001:8080"
    restart: unless-stopped
    environment:
      - DOTNET_ENVIRONMENT=Production
      - APP_ENV=production
    